[package]
name = "ghe2d"
version = "0.0.2"
license = "ISC"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ghe2d = "0.0.4"
